"""Provider abstraction for prompt→spec generation (T2.4).

One function — ``complete(system, user)`` — behind which DeepSeek, OpenAI,
and Anthropic adapters live. Environment variables select and configure the
provider:

    LLM_PROVIDER   deepseek (default) | openai | anthropic | mock
    LLM_MODEL      optional model override
    DEEPSEEK_API_KEY / OPENAI_API_KEY / ANTHROPIC_API_KEY

``mock`` needs no key and returns a canned spec — used by the test suite and
for trying the UI before you have an API key.
"""
from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Iterator

import httpx

TIMEOUT = 90.0
REPO_ROOT = Path(__file__).resolve().parents[2]

#: DeepSeek models the UI dropdown may request. Anything outside this set is
#: ignored (falls back to the env default) so a client can never inject an
#: arbitrary model string.
DEEPSEEK_MODELS = ("deepseek-chat", "deepseek-v4-flash", "deepseek-v4-pro")
DEFAULT_DEEPSEEK_MODEL = "deepseek-chat"


def resolve_model(provider: str, requested: str | None) -> str:
    """Pick the model id for a provider: an allowlisted per-request override
    (DeepSeek only) beats the LLM_MODEL env default, which beats the built-in
    default. Returns "" for providers whose caller supplies its own default."""
    env_model = os.environ.get("LLM_MODEL", "").strip()
    if provider == "deepseek":
        if requested and requested.strip() in DEEPSEEK_MODELS:
            return requested.strip()
        return env_model or DEFAULT_DEEPSEEK_MODEL
    return env_model


class LLMError(RuntimeError):
    """Configuration or transport failure talking to the LLM provider."""


def _require_key(env_var: str) -> str:
    key = os.environ.get(env_var, "").strip()
    if not key:
        raise LLMError(
            f"{env_var} is not set. Add it to your environment (on Vercel: "
            f"Project → Settings → Environment Variables), then restart/redeploy."
        )
    return key


def _openai_compatible(url: str, api_key: str, model: str, system: str, user: str,
                       temperature: float, max_tokens: int) -> str:
    resp = httpx.post(
        url,
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
        },
        timeout=TIMEOUT,
    )
    if resp.status_code != 200:
        raise LLMError(f"LLM provider returned {resp.status_code}: {resp.text[:300]}")
    return resp.json()["choices"][0]["message"]["content"]


def _anthropic(api_key: str, model: str, system: str, user: str,
               temperature: float, max_tokens: int) -> str:
    resp = httpx.post(
        "https://api.anthropic.com/v1/messages",
        headers={"x-api-key": api_key, "anthropic-version": "2023-06-01"},
        json={
            "model": model,
            "system": system,
            "messages": [{"role": "user", "content": user}],
            "temperature": temperature,
            "max_tokens": max_tokens,
        },
        timeout=TIMEOUT,
    )
    if resp.status_code != 200:
        raise LLMError(f"LLM provider returned {resp.status_code}: {resp.text[:300]}")
    return resp.json()["content"][0]["text"]


def _mock(user: str) -> str:
    """Keyless demo/test provider: canned responses per request kind."""
    if user.startswith("ENHANCE PROMPT"):
        request = user.split("Request:", 1)[-1].strip()
        return (
            f"Design brief: {request}. Code-compliant, galvanized-steel or "
            "cast-iron structure with a clear load path to a base plate at "
            "grade; members joined by through-bolts or band clamps; sliders "
            "for the principal dimensions and toggles for optional features."
        )
    if user.startswith("INSTALL GUIDE"):
        return (
            "## Overview\nA parametric asset generated by AssetForge (mock guide — "
            "configure a real LLM provider for a tailored one).\n\n"
            "## Tools & materials\n- Anchor bolts, nuts, washers\n- Torque wrench, level\n\n"
            "## Site preparation\n1. Verify utility clearances.\n2. Pour footing per local code.\n\n"
            "## Assembly sequence\n1. Set base plate over anchor bolts.\n2. Erect and plumb the asset.\n"
            "3. Torque nuts evenly.\n\n"
            "## Code compliance checklist\n- Confirm dimensions against the citations in the spec.\n\n"
            "## Inspection & maintenance\nInspect fasteners annually.\n\n"
            "*Safety: a licensed engineer must approve structural anchoring for public installations.*"
        )
    if user.startswith("STANDARDS UPDATE"):
        db = json.loads((REPO_ROOT / "standards" / "us_codes.json").read_text(encoding="utf-8"))
        db["_meta"]["version"] = int(db["_meta"].get("version", 1)) + 1
        db["bike_rack"] = {
            "source": "APBP Essentials of Bike Parking (mock demo entry)",
            "parameters": {
                "height": {"min": 30, "max": 36, "default": 33, "unit": "in",
                            "code_ref": "APBP-2.2", "note": "Mock demo entry."},
            },
        }
        return json.dumps(db)
    name = "park_bench.json" if "bench" in user.lower() else "street_light.json"
    return (REPO_ROOT / "examples" / name).read_text(encoding="utf-8")


def complete(system: str, user: str, *, temperature: float = 0.4,
             max_tokens: int = 6000, model: str | None = None) -> str:
    provider = os.environ.get("LLM_PROVIDER", "deepseek").strip().lower()
    picked = resolve_model(provider, model)

    if provider == "mock":
        return _mock(user)
    if provider == "deepseek":
        return _openai_compatible(
            "https://api.deepseek.com/v1/chat/completions",
            _require_key("DEEPSEEK_API_KEY"), picked or DEFAULT_DEEPSEEK_MODEL,
            system, user, temperature, max_tokens,
        )
    if provider == "openai":
        return _openai_compatible(
            "https://api.openai.com/v1/chat/completions",
            _require_key("OPENAI_API_KEY"), picked or "gpt-4o-mini",
            system, user, temperature, max_tokens,
        )
    if provider == "anthropic":
        return _anthropic(
            _require_key("ANTHROPIC_API_KEY"), picked or "claude-sonnet-5",
            system, user, temperature, max_tokens,
        )
    raise LLMError(
        f"Unknown LLM_PROVIDER {provider!r} (expected deepseek, openai, anthropic, or mock)"
    )


# ---------------------------------------------------------------------------
# Streaming variants — yield text chunks as the provider produces them.
# ---------------------------------------------------------------------------

def _openai_compatible_stream(url: str, api_key: str, model: str, system: str,
                              user: str, temperature: float, max_tokens: int) -> Iterator[str]:
    with httpx.stream(
        "POST", url,
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": True,
        },
        timeout=TIMEOUT,
    ) as resp:
        if resp.status_code != 200:
            resp.read()
            raise LLMError(f"LLM provider returned {resp.status_code}: {resp.text[:300]}")
        for line in resp.iter_lines():
            if not line.startswith("data:"):
                continue
            data = line[5:].strip()
            if data == "[DONE]":
                break
            try:
                delta = json.loads(data)["choices"][0]["delta"].get("content")
            except (KeyError, IndexError, json.JSONDecodeError):
                continue
            if delta:
                yield delta


def _anthropic_stream(api_key: str, model: str, system: str, user: str,
                      temperature: float, max_tokens: int) -> Iterator[str]:
    with httpx.stream(
        "POST", "https://api.anthropic.com/v1/messages",
        headers={"x-api-key": api_key, "anthropic-version": "2023-06-01"},
        json={
            "model": model,
            "system": system,
            "messages": [{"role": "user", "content": user}],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": True,
        },
        timeout=TIMEOUT,
    ) as resp:
        if resp.status_code != 200:
            resp.read()
            raise LLMError(f"LLM provider returned {resp.status_code}: {resp.text[:300]}")
        for line in resp.iter_lines():
            if not line.startswith("data:"):
                continue
            try:
                event = json.loads(line[5:].strip())
            except json.JSONDecodeError:
                continue
            if event.get("type") == "content_block_delta":
                text = event.get("delta", {}).get("text")
                if text:
                    yield text


def complete_stream(system: str, user: str, *, temperature: float = 0.4,
                    max_tokens: int = 6000, model: str | None = None) -> Iterator[str]:
    """Streaming twin of :func:`complete`."""
    provider = os.environ.get("LLM_PROVIDER", "deepseek").strip().lower()
    picked = resolve_model(provider, model)

    if provider == "mock":
        text = _mock(user)
        for i in range(0, len(text), 64):  # simulate token flow for the UI
            yield text[i : i + 64]
            time.sleep(0.004)
        return
    if provider == "deepseek":
        yield from _openai_compatible_stream(
            "https://api.deepseek.com/v1/chat/completions",
            _require_key("DEEPSEEK_API_KEY"), picked or DEFAULT_DEEPSEEK_MODEL,
            system, user, temperature, max_tokens,
        )
        return
    if provider == "openai":
        yield from _openai_compatible_stream(
            "https://api.openai.com/v1/chat/completions",
            _require_key("OPENAI_API_KEY"), picked or "gpt-4o-mini",
            system, user, temperature, max_tokens,
        )
        return
    if provider == "anthropic":
        yield from _anthropic_stream(
            _require_key("ANTHROPIC_API_KEY"), picked or "claude-sonnet-5",
            system, user, temperature, max_tokens,
        )
        return
    raise LLMError(
        f"Unknown LLM_PROVIDER {provider!r} (expected deepseek, openai, anthropic, or mock)"
    )
